<?xml version="1.0"?>

<!DOCTYPE residueTable [
  <!ELEMENT residueTable (residue)*>
  <!ELEMENT residue (property)*>
  <!ATTLIST residue token ID #IMPLIED>
  <!ELEMENT property (#PCDATA)>

  <!ATTLIST property name CDATA #REQUIRED
                     value CDATA #REQUIRED>

]>

<residueTable>
  <!-- The Residue masses were obtained from the Micromass reference table
  http://www.micromass.co.uk/resources/reference_tables/refp1s1.asp
    -->
  <residue token="A">
    <property name="monoMass" value="71.03711"/>
    <property name="avgMass" value="71.0788"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="R">
    <property name="monoMass" value="156.10111"/>
    <property name="avgMass" value="156.1876"/>
    <property name="pK" value="12.50"/>
  </residue>
  <residue token="N">
    <property name="monoMass" value="114.04293"/>
    <property name="avgMass" value="114.1039"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="D">
    <property name="monoMass" value="115.02694"/>
    <property name="avgMass" value="115.0886"/>
    <property name="pK" value="-3.91"/>
  </residue>
  <residue token="C">
    <property name="monoMass" value="103.00919"/>
    <property name="avgMass" value="103.1448"/>
    <property name="pK" value="-8.3"/>
  </residue>
  <residue token="E">
    <property name="monoMass" value="129.04259"/>
    <property name="avgMass" value="129.1155"/>
    <property name="pK" value="-4.25"/>
  </residue>
  <residue token="Q">
    <property name="monoMass" value="128.05858"/>
    <property name="avgMass" value="128.1308"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="G">
    <property name="monoMass" value="57.02146"/>
    <property name="avgMass" value="57.0520"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="H">
    <property name="monoMass" value="137.05891"/>
    <property name="avgMass" value="137.1412"/>
    <property name="pK" value="6.5"/>
  </residue>
  <residue token="I">
    <property name="monoMass" value="113.08406"/>
    <property name="avgMass" value="113.1595"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="L">
    <property name="monoMass" value="113.08406"/>
    <property name="avgMass" value="113.1595"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="K">
    <property name="monoMass" value="128.09496"/>
    <property name="avgMass" value="128.1742"/>
    <property name="pK" value="10.79"/>
  </residue>
  <residue token="M">
    <property name="monoMass" value="131.04049"/>
    <property name="avgMass" value="131.1986"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="F">
    <property name="monoMass" value="147.06841"/>
    <property name="avgMass" value="147.1766"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="P">
    <property name="monoMass" value="97.05276"/>
    <property name="avgMass" value="97.1167"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="S">
    <property name="monoMass" value="87.03203"/>
    <property name="avgMass" value="87.0782"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="T">
    <property name="monoMass" value="101.04768"/>
    <property name="avgMass" value="101.1051"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="W">
    <property name="monoMass" value="186.07931"/>
    <property name="avgMass" value="186.2133"/>
    <property name="pK" value="0.0"/>
  </residue>
  <residue token="Y">
    <property name="monoMass" value="163.06333"/>
    <property name="avgMass" value="163.1760"/>
    <property name="pK" value="-10.95"/>
  </residue>
  <residue token="V">
    <property name="monoMass" value="99.0684"/>
    <property name="avgMass" value="99.1326"/>
    <property name="pK" value="0.0"/>
  </residue>
</residueTable>
